// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/common/Header";
import { QueryProvider } from "@/components/common/QueryProvider";
import SmoothScrollProvider from "@/components/common/SmoothScrollProvider";
// import { Playfair_Display, Inter } from "next/font/google";
import localFont from "next/font/local";

// const playfair = Playfair_Display({
//   subsets: ["latin"],
//   weight: ["500", "600", "700"],
//   variable: "--font-heading",
// });

// const inter = Inter({
//   subsets: ["latin"],
//   weight: ["300", "400", "500", "600"],
//   variable: "--font-body",
// });

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });



// Geist Font Placeholder Setup
const geist = localFont({
  src: [
    {
      path: "./fonts/Geist-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Geist-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Geist-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/Geist-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-geist",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body className={`${playfair.variable} ${inter.variable} relative`}> */}
      <body className={`${geist.variable} relative`}>

        <Header />

        <div id="smooth-wrapper" className="pt-[64px]">
          <div id="smooth-content">
            <SmoothScrollProvider>
              <QueryProvider>
                {children}
              </QueryProvider>
            </SmoothScrollProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
