// import { Geist, Geist_Mono } from "next/font/google";
import Footer from "@/components/common/Footer";
import "./globals.css";
import Header from "@/components/common/Header";
import { QueryProvider } from "@/components/common/QueryProvider";
import SmoothScrollProvider from "@/components/common/SmoothScrollProvider";
// import { Playfair_Display, Inter } from "next/font/google";
import localFont from "next/font/local";
import GsapAnimationProvider from "@/components/common/GsapAnimationProvider";

// Geist Font Placeholder Setup
const geist = localFont({
  src: [
    {
      path: "./fonts/Geist-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Geist-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Geist-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/Geist-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-geist",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geist.variable} relative`}>
        <Header />
        <SmoothScrollProvider>
          <QueryProvider>
            <div className="pt-[60px]">
              <GsapAnimationProvider>
                {children}
              </GsapAnimationProvider>
              <Footer />
            </div>
          </QueryProvider>
        </SmoothScrollProvider>
      </body>
    </html>
  );
}
